# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfdde9d5a0bb4f1bd699c39cd6d10655982867a43b6d783fa6d09507b2d8b8566aabf08f394acc449c44547d22bd941c55a08072be7a6603e200de54d1272189

test:
  secret_key_base: 1cf9800d991abd1016742d089c19fab6fbe70ad0e4f660d15ebbbb8bf23caf45ae2b02783cbb539e738ff5bd253378b500c559ed111831d9b83ee392a61e2141

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
